#include<iostream.h>
#include<conio.h>

// Based on Machine Problem 5

// technically I'm not going to make a guide of this but ehhhhh you do you

void main()
{
 clrscr();

 cout<<"\n   EEEEEEEEEEEEEEEE     CCCCCCCCCCCCCCCC    SSSSSSSSSSSSSSSS   PPPPPPPPPPPPPPP";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n   E                    C                   S                  P             P";
 cout<<"\n
 cout<<"\n   E                    C                                  S   P";
 cout<<"\n   E                    C                                  S   P";
 cout<<"\n   E                    C                                  S   P";
 cout<<"\n   E                    C                                  S   P";
 cout<<"\n   E                    C                                  S   P";
 cout<<"\n
 cout<<"\n
 cout<<"\n
 cout<<"\n
 cout<<"\n
 getch();
}
