#include<iostream.h>  // these two libraries are needed to get the code below running
#include<conio.h>

// Based on Machine Problem 6

void main()

 int days=0; // example
 clrscr();

 // cout<< decide which is your basis to do your computation
 // then cin>>[variable]
 // formula
 months=weeks/4.34524; // example

 cout<<"\nWeeks: "<<weeks;
 cout<<"\nMonths: "<<months; // then display
 cout<<"\nYears: "<<years;
 getch();
}
